# Generated by Django 4.1.6 on 2023-03-21 04:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cc', models.CharField(max_length=10)),
                ('entity', models.CharField(choices=[('EPS', 'EPS'), ('ARL', 'ARL'), ('IPS', 'IPS'), ('PARTICULAR', 'Particular')], default='IPS', max_length=10)),
                ('entity_name', models.CharField(default='OTTOBOCK', max_length=30)),
                ('new_client', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2)),
                ('companion_required', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2)),
                ('activity', models.CharField(default='SATISFACTORIO', max_length=30)),
                ('drawbacks', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2)),
                ('drawbacks_description', models.CharField(blank=True, max_length=100)),
                ('technosurveillance', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2)),
                ('technosurveillance_id', models.IntegerField(blank=True, null=True)),
                ('technosurveillance_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('requirement', models.CharField(choices=[('ENTRENAMIENTO', 'ENTRENAMIENTO'), ('GARANTIA', 'GARANTIA'), ('MANTENIMIENTO', 'MANTENIMIENTO'), ('REPARACION', 'REPARACION'), ('VALORACION', 'VALORACION'), ('TOMA DE MEDIDAS', 'TOMA DE MEDIDAS'), ('PRUEBA DE DISPOSITIVO', 'PRUEBA DE DISPOSITIVO')], default='TOMA DE MEDIDAS', max_length=30)),
                ('description', models.CharField(default='Usuario asiste para toma de medidas', max_length=100)),
                ('new_appointment', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2)),
                ('new_appointment_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_documents.patient')),
            ],
        ),
    ]
