# Generated by Django 4.1.6 on 2023-04-26 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cc', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('entity', models.CharField(choices=[('EPS', 'EPS'), ('ARL', 'ARL'), ('IPS', 'IPS'), ('PARTICULAR', 'Particular')], default='IPS', max_length=10)),
                ('entity_name', models.CharField(default='OTTOBOCK', max_length=30)),
                ('companion_required', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2)),
                ('signature', models.ImageField(null=True, upload_to='signatures')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_material_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Traceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=10)),
                ('purchase_date', models.DateField()),
                ('supplies', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('supplier', models.CharField(max_length=60)),
                ('batch_number', models.CharField(blank=True, max_length=30)),
                ('invima_registry', models.CharField(blank=True, max_length=30)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('value', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_documents.product')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_documents.rawmaterial')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='raw_materials',
            field=models.ManyToManyField(through='user_documents.RawMaterialQuantity', to='user_documents.rawmaterial'),
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.CharField(choices=[('Nuevo', 'New'), ('Existente', 'Existing')], default='Nuevo', max_length=9)),
                ('requirement', models.CharField(choices=[('ENTRENAMIENTO', 'ENTRENAMIENTO'), ('GARANTIA', 'GARANTIA'), ('MANTENIMIENTO', 'MANTENIMIENTO'), ('REPARACION', 'REPARACION'), ('VALORACION', 'VALORACION'), ('TOMA DE MEDIDAS', 'TOMA DE MEDIDAS'), ('PRUEBA DE DISPOSITIVO', 'PRUEBA DE DISPOSITIVO'), ('PRUEBA Y ENTREGA DE DISPOSITIVO', 'PRUEBA Y ENTREGA DE DISPOSITIVO')], default='TOMA DE MEDIDAS', max_length=35)),
                ('description', models.CharField(default='Usuario asiste para toma de medidas', max_length=100)),
                ('activity', models.CharField(default='SATISFACTORIO', max_length=30)),
                ('reported_drawbacks', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2)),
                ('drawbacks_description', models.CharField(blank=True, max_length=100)),
                ('technosurveillance', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2)),
                ('technosurveillance_id', models.IntegerField(blank=True, null=True)),
                ('technosurveillance_date', models.DateField(blank=True, null=True)),
                ('new_appointment', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2)),
                ('new_appointment_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_documents.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_documents.product'),
        ),
    ]
