# Generated by Django 4.1.6 on 2023-04-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=10)),
                ('product', models.ForeignKey(on_delete=models.deletion.CASCADE, to='user_documents.Product')),
                ('raw_material', models.ForeignKey(on_delete=models.deletion.CASCADE, to='user_documents.RawMaterial')),
            ],
        ),
    ]
