# Generated by Django 4.1.6 on 2023-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='drawbacks',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='new_client',
        ),
        migrations.AddField(
            model_name='patient',
            name='client',
            field=models.CharField(choices=[('New', 'New'), ('Existing', 'Existing')], default='New', max_length=8),
        ),
        migrations.AddField(
            model_name='patient',
            name='reported_drawbacks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='companion_required',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='new_appointment',
            field=models.BooleanField(),
        ),
    ]
