# Generated by Django 4.1.6 on 2023-03-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_documents', '0003_alter_patient_reported_drawbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='client',
            field=models.BooleanField(choices=[('New', 'New'), ('Existing', 'Existing')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='companion_required',
            field=models.BooleanField(choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reported_drawbacks',
            field=models.BooleanField(choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='technosurveillance',
            field=models.BooleanField(choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
    ]
