# Generated by Django 4.1.6 on 2023-03-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_documents', '0004_alter_patient_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='client',
            field=models.CharField(choices=[('New', 'New'), ('Existing', 'Existing')], default='New', max_length=8),
        ),
        migrations.AlterField(
            model_name='patient',
            name='companion_required',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reported_drawbacks',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='technosurveillance',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='new_appointment',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2),
        ),
    ]
