# Generated by Django 4.1.6 on 2023-03-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_documents', '0005_alter_patient_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='companion_required',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reported_drawbacks',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
    ]
