# Generated by Django 4.1.6 on 2023-03-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_documents', '0006_alter_patient_companion_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='client',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='client',
            field=models.CharField(choices=[('New', 'New'), ('Existing', 'Existing')], default='New', max_length=8),
        ),
    ]
