# Generated by Django 4.1.6 on 2023-03-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_documents', '0007_remove_patient_client_patientrecord_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=10)),
                ('purchase_date', models.DateField()),
                ('supplies', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('supplier', models.CharField(max_length=30)),
                ('batch_number', models.CharField(max_length=30)),
                ('invima_registry', models.CharField(max_length=30)),
                ('expiration_date', models.DateField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='drawbacks_description',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='reported_drawbacks',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='technosurveillance',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='technosurveillance_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='technosurveillance_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='product_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='activity',
            field=models.CharField(default='SATISFACTORIO', max_length=30),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='drawbacks_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='reported_drawbacks',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='technosurveillance',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='technosurveillance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='technosurveillance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='client',
            field=models.CharField(choices=[('Nuevo', 'New'), ('Existente', 'Existing')], default='Nuevo', max_length=9),
        ),
    ]
