# Generated by Django 4.1.6 on 2023-03-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_documents', '0008_traceability_remove_patient_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceability',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='traceability',
            name='batch_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='traceability',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traceability',
            name='invima_registry',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
