# Generated by Django 4.1.6 on 2023-03-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_documents', '0009_alter_traceability_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceability',
            name='supplies',
            field=models.CharField(max_length=40),
        ),
    ]
