# Generated by Django 4.1.6 on 2023-03-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_documents', '0014_rawmaterial_product_alter_patient_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='signature',
            field=models.ImageField(null=True, upload_to='signatures'),
        ),
    ]
