# Generated by Django 4.1.6 on 2023-04-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_documents', '0015_patient_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
