# Generated by Django 4.1.6 on 2023-04-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_documents', '0017_alter_patient_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='requirement',
            field=models.CharField(choices=[('ENTRENAMIENTO', 'ENTRENAMIENTO'), ('GARANTIA', 'GARANTIA'), ('MANTENIMIENTO', 'MANTENIMIENTO'), ('REPARACION', 'REPARACION'), ('VALORACION', 'VALORACION'), ('TOMA DE MEDIDAS', 'TOMA DE MEDIDAS'), ('PRUEBA DE DISPOSITIVO', 'PRUEBA DE DISPOSITIVO'), ('PRUEBA DE DISPOSITIVO', 'PRUEBA Y ENTREGA DE DISPOSITIVO')], default='TOMA DE MEDIDAS', max_length=30),
        ),
    ]
